language: go

go:
  - 1.4.2
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

services:

before_install:

install:
  - go get github.com/northbright/httputil
  - go get github.com/northbright/pathhelper
  - go get github.com/gin-gonic/gin

script:
  - cd $TRAVIS_BUILD_DIR/client && go build -v
  - cd $TRAVIS_BUILD_DIR/server && go build -v
